% Track data
Trackname = "Spa-Francorchamps";

spa_track(1) = struct( ...
    'name', "Start Straight", ...
    'type', "straight", ...
    'length', 368, ...
    'width', 17, ...
    'radius', [], ...
    'direction', "" ...
);

spa_track(2) = struct( ...
    'name', "La Source", ...
    'type', "corner", ...
    'length', 60, ...
    'width', 9, ...
    'radius', 35, ...
    'direction', "R" ...
);

spa_track(3) = struct( ...
    'name', "Eau Rouge Entry", ...
    'type', "straight", ...
    'length', 580, ...
    'width', 9, ...
    'radius', [], ...
    'direction', "" ...
);

spa_track(4) = struct( ...
    'name', "Eau Rouge", ...
    'type', "corner", ...
    'length', 160, ...
    'width', 9, ...
    'radius', 190, ...
    'direction', "L" ...
);

spa_track(5) = struct( ...
    'name', "Raidillon", ...
    'type', "corner", ...
    'length', 420, ...
    'width', 9, ...
    'radius', 250, ...
    'direction', "R" ...
);

spa_track(6) = struct( ...
    'name', "Kemmel Straight", ...
    'type', "straight", ...
    'length', 800, ...
    'width', 9, ...
    'radius', [], ...
    'direction', "" ...
);

spa_track(7) = struct( ...
    'name', "Les Combes P1", ...
    'type', "corner", ...
    'length', 82, ...
    'width', 9, ...
    'radius', 60, ...
    'direction', "R" ...
);

spa_track(8) = struct( ...
    'name', "Les Combes P2", ...
    'type', "corner", ...
    'length', 78, ...
    'width', 9, ...
    'radius', 60, ...
    'direction', "L" ...
);

spa_track(9) = struct( ...
    'name', "Les Combes P3", ...
    'type', "straight", ...
    'length', 80, ...
    'width', 9, ...
    'radius', [], ...
    'direction', "" ...
);

spa_track(10) = struct( ...
    'name', "Les Combes P4", ...
    'type', "corner", ...
    'length', 64, ...
    'width', 9, ...
    'radius', 75, ...
    'direction', "L" ...
);

spa_track(11) = struct( ...
    'name', "Bruxelles P1", ...
    'type', "straight", ...
    'length', 285, ...
    'width', 9, ...
    'radius', [], ...
    'direction', "" ...
);

spa_track(12) = struct( ...
    'name', "Bruxelles P2", ...
    'type', "corner", ...
    'length', 172, ...
    'width', 9, ...
    'radius', 120, ...
    'direction', "R" ...
);

spa_track(13) = struct( ...
    'name', "Bruxelles P3", ...
    'type', "straight", ...
    'length', 127, ...
    'width', 9, ...
    'radius', [], ...
    'direction', "" ...
);

spa_track(14) = struct( ...
    'name', "No Name", ...
    'type', "corner", ...
    'length', 64, ...
    'width', 9, ...
    'radius', 110, ...
    'direction', "L" ...
);

spa_track(15) = struct( ...
    'name', "Pouho P1", ...
    'type', "straight", ...
    'length', 445, ...
    'width', 9, ...
    'radius', [], ...
    'direction', "" ...
);

spa_track(16) = struct( ...
    'name', "Pouhon P2", ...
    'type', "corner", ...
    'length', 375, ...
    'width', 9, ...
    'radius', 160, ...
    'direction', "L" ...
);

spa_track(17) = struct( ...
    'name', "Pouhon P3", ...
    'type', "straight", ...
    'length', 315, ...
    'width', 9, ...
    'radius', [], ...
    'direction', "" ...
);

spa_track(18) = struct( ...
    'name', "Fagnes P1", ...
    'type', "corner", ...
    'length', 160, ...
    'width', 9, ...
    'radius', 70, ...
    'direction', "R" ...
);

spa_track(19) = struct( ...
    'name', "Fagnes P2", ...
    'type', "corner", ...
    'length', 145, ...
    'width', 9, ...
    'radius', 70, ...
    'direction', "L" ...
);

spa_track(20) = struct( ...
    'name', "Fagnes P3", ...
    'type', "straight", ...
    'length', 183, ...
    'width', 9, ...
    'radius', [], ...
    'direction', "" ...
);

spa_track(21) = struct( ...
    'name', "Campus P1", ...
    'type', "corner", ...
    'length', 90, ...
    'width', 9, ...
    'radius', 60, ...
    'direction', "R" ...
);

spa_track(22) = struct( ...
    'name', "Campus P2", ...
    'type', "straight", ...
    'length', 113, ...
    'width', 9, ...
    'radius', [], ...
    'direction', "" ...
);

spa_track(23) = struct( ...
    'name', "Stavelot", ...
    'type', "corner", ...
    'length', 200, ...
    'width', 9, ...
    'radius', 160, ...
    'direction', "R" ...
);

spa_track(24) = struct( ...
    'name', "Paul Frere P1", ...
    'type', "straight", ...
    'length', 500, ...
    'width', 9, ...
    'radius', [], ...
    'direction', "" ...
);

spa_track(25) = struct( ...
    'name', "Paul Frere P2", ...
    'type', "corner", ...
    'length', 180, ...
    'width', 9, ...
    'radius', 75, ...
    'direction', "L" ...
);

spa_track(26) = struct( ...
    'name', "Paul Frere P3", ...
    'type', "straight", ...
    'length', 190, ...
    'width', 9, ...
    'radius', [], ...
    'direction', "" ...
);

spa_track(27) = struct( ...
    'name', "Blanchimont", ...
    'type', "corner", ...
    'length', 100, ...
    'width', 9, ...
    'radius', 250, ...
    'direction', "L" ...
);

spa_track(28) = struct( ...
    'name', "Bus Stop P1", ...
    'type', "straight", ...
    'length', 465, ...
    'width', 9, ...
    'radius', [], ...
    'direction', "" ...
);

spa_track(29) = struct( ...
    'name', "Bus Stop P2", ...
    'type', "corner", ...
    'length', 50, ...
    'width', 9, ...
    'radius', 45, ...
    'direction', "R" ...
);

spa_track(30) = struct( ...
    'name', "Bus Stop P3", ...
    'type', "corner", ...
    'length', 60, ...
    'width', 9, ...
    'radius', 45, ...
    'direction', "L" ...
);

spa_track(31) = struct( ...
    'name', "Pit Straight", ...
    'type', "straight", ...
    'length', 153, ...
    'width', 9, ...
    'radius', [], ...
    'direction', "" ...
);